
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 110
#define YY_END_OF_BUFFER 111
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[406] =
    {   0,
        0,    0,  111,  109,  108,  108,   96,  109,  102,   95,
      109,   90,   91,  100,   99,   87,   98,   94,  101,   53,
       52,   88,   84,  103,   89,  104,  107,   50,   50,   92,
       93,  105,   50,   50,   50,   50,   50,   50,   50,   50,
       50,   50,   50,   50,   50,   50,   50,   50,   85,  106,
       86,   97,  108,   83,    0,   61,    0,   69,   86,   78,
       70,    0,    0,   67,   75,   65,   76,   66,   77,    0,
       56,    1,    2,   68,   57,   53,    0,    0,   53,   53,
        0,   53,   52,   52,   52,   52,   93,   85,   92,   74,
       80,   82,   81,   73,   50,    0,    0,   71,   50,   50,

       50,   50,   50,   50,   50,   50,   50,   50,   50,   50,
       50,   50,   50,   11,   50,   50,   50,   50,   50,   50,
       19,   50,   50,   50,   50,   50,   50,   50,   50,   50,
       50,   50,   50,   72,   79,   61,    0,    0,    0,    0,
       54,    0,    0,   62,    0,   56,    2,    0,   57,    0,
       55,   53,   53,   53,   53,    0,   51,   52,   52,   52,
       52,   64,   63,   50,   50,   50,   50,   50,   50,   50,
       50,   50,   50,   50,   50,   50,   50,   50,   50,   50,
       50,   50,   50,   50,   50,   17,   50,   50,   21,   50,
       50,   50,   50,   50,   50,   50,   50,   50,   50,   50,

       50,   50,   50,   50,   50,    0,    0,    0,    0,    0,
       56,    0,   57,   55,   53,    0,    0,   51,    0,   51,
       51,   52,   50,   50,   50,   50,   50,   50,   50,   50,
       50,   50,   50,    4,   50,    6,    7,   50,   50,   50,
       50,   13,   14,   50,   50,   18,   50,   22,   50,   50,
       50,   50,   50,   50,   50,   50,   50,   50,   50,   50,
       35,   50,   50,    0,    0,    0,    0,    0,    0,   51,
       51,    0,   58,   51,   51,   50,   50,   42,   50,   50,
       50,   50,   50,   50,   50,   50,    5,    8,   50,   50,
       50,   50,   16,   50,   50,   50,   50,   26,   50,   50,

       50,   50,   50,   50,   33,   50,   50,   37,    0,   59,
        0,   60,   58,   51,   50,   50,   50,   50,   50,   50,
       50,   50,   50,   50,   50,   50,   12,   15,   20,   50,
       50,   25,   27,   28,   29,   30,   31,   50,   50,   50,
       59,   60,   50,   50,   41,   50,   50,   50,   50,   50,
       50,   50,   50,   50,   10,   50,   50,   32,   50,   50,
       38,   39,    0,   40,   43,   44,   50,   50,   50,   50,
       50,   49,    9,   23,   24,   34,   36,   50,   46,   50,
       50,   50,   45,   50,   50,   50,   50,   50,   50,   50,
       50,   50,   50,   48,   50,   47,    0,    0,    0,    0,

        0,    0,    0,    3,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        2,    2,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    1,    1,    7,    8,    9,   10,
       11,   12,   13,   14,   15,   16,   17,   18,   19,   19,
       19,   19,   19,   19,   19,   20,   21,   22,   23,   24,
       25,   26,   27,    1,   28,   29,   30,   31,   32,   33,
       34,   35,   36,   35,   35,   37,   35,   38,   35,   39,
       35,   35,   40,   41,   42,   35,   35,   43,   35,   35,
       44,   45,   46,   47,   48,    1,   49,   50,   51,   52,

       53,   54,   55,   56,   57,   35,   58,   59,   60,   61,
       62,   63,   35,   64,   65,   66,   67,   68,   69,   70,
       71,   72,   73,   74,   75,   76,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[77] =
    {   0,
        1,    1,    2,    1,    1,    3,    1,    1,    4,    1,
        1,    1,    1,    1,    1,    5,    1,    6,    6,    7,
        7,    1,    1,    1,    1,    1,    3,    7,    7,    7,
        7,    7,    7,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    1,    3,    1,    1,    8,    6,    6,
        7,    7,    7,    6,    8,    8,    8,    8,    8,    8,
        9,    8,    8,    9,    8,    9,    8,    9,    8,    9,
        8,    8,    1,    1,    1,    1
    } ;

static const flex_int16_t yy_base[417] =
    {   0,
        0,    0,  746,  747,   75,   78,  720,   77,   59,   78,
      699,  747,  747,  718,   74,  747,   75,   73,   85,  107,
       98,  716,  747,  130,  716,   70,  747,    0,   98,  747,
      747,  715,  142,  672,  674,   49,   53,   72,   50,  675,
       59,  674,  682,   90,  663,  123,  671,  676,  747,   99,
      747,  747,  159,  747,  130,  183,  149,  747,  747,  747,
      747,  136,  173,  747,  747,  747,  747,  747,  747,  715,
      175,  747,    0,  747,  185,  195,  237,  246,  184,  142,
      714,  182,  252,  193,  151,  221,  747,  747,  747,  704,
      747,  747,  747,  703,    0,  152,  682,  747,   75,  664,

      663,  671,  663,  660,  655,  664,   99,  653,  665,  652,
      667,  654,  660,  646,  647,  644,  644,  647,  644,  641,
        0,  143,  645,  181,  643,   66,  227,  647,  640,  696,
      166,  141,  644,  747,  747,  275,  694,  276,  268,    0,
      747,  283,    0,  747,  303,  747,    0,  312,  747,  279,
      316,  241,  747,  662,  639,    0,  304,  243,  747,  660,
      637,  747,  747,  638,  632,  631,  632,  630,  641,  625,
      639,  623,  620,  618,  622,  634,  629,  617,  238,  631,
      629,  625,  617,  623,  626,    0,  612,  616,    0,  617,
      614,  604,  602,  604,  606,  613,  599,  597,  597,  609,

      599,  603,  607,  609,  598,  320,  370,  336,  416,  338,
      359,  364,  420,  747,  747,  301,  305,  375,  462,  256,
      327,  747,  601,  595,  595,  590,  599,  596,  597,  583,
      595,  581,  585,    0,  587,    0,    0,  578,  586,  575,
      582,    0,    0,  576,  573,    0,  577,    0,  572,  572,
      546,  541,  553,  542,  543,  548,  546,  533,  522,  519,
        0,  505,  517,  269,    0,  342,    0,  471,  480,  305,
      747,  386,  484,  532,  509,  505,  508,    0,  505,  499,
      505,  495,  503,  510,  494,  506,    0,    0,  495,  496,
      501,  492,    0,  499,  485,  491,  486,    0,  493,  488,

      490,  474,  483,  484,    0,  475,  478,    0,  390,  490,
      408,  513,  747,  747,  299,  479,  476,  471,  465,  458,
      473,  470,  463,  471,  451,  450,    0,    0,    0,  462,
      463,    0,    0,    0,    0,    0,    0,  459,  454,  438,
      747,  747,  431,  433,  448,  415,  425,  424,  407,  416,
      415,  410,  411,  390,    0,  369,  366,    0,  379,  377,
        0,    0,  452,  747,    0,    0,  352,  353,  348,  336,
      326,    0,    0,    0,    0,    0,    0,  303,    0,  308,
      300,  286,    0,  285,  278,  256,  254,  257,  247,  178,
      140,  121,   98,    0,  356,    0,  468,  484,  502,   97,

       77,  229,  241,  747,  747,  572,  581,  585,  592,  599,
      608,  613,  615,  617,  619,  626
    } ;

static const flex_int16_t yy_def[417] =
    {   0,
      405,    1,  405,  405,  405,  405,  405,  406,  405,  405,
      407,  405,  405,  405,  405,  405,  405,  405,  405,  405,
      405,  405,  405,  405,  405,  405,  405,  408,  408,  405,
      405,  405,  408,  408,  408,  408,  408,  408,  408,  408,
      408,  408,  408,  408,  408,  408,  408,  408,  405,  405,
      405,  405,  405,  405,  406,  405,  409,  405,  405,  405,
      405,  407,  410,  405,  405,  405,  405,  405,  405,  405,
      405,  405,  411,  405,  405,  405,  405,  405,  405,  405,
      412,  405,  405,  405,  405,  405,  405,  405,  405,  405,
      405,  405,  405,  405,  408,  406,  407,  405,  408,  408,

      408,  408,  408,  408,  408,  408,  408,  408,  408,  408,
      408,  408,  408,  408,  408,  408,  408,  408,  408,  408,
      408,  408,  408,  408,  408,  408,  408,  408,  408,  408,
      408,  408,  408,  405,  405,  405,  405,  405,  406,  413,
      405,  407,  414,  405,  405,  405,  411,  405,  405,  405,
      405,  405,  405,  405,  405,  415,  412,  405,  405,  405,
      405,  405,  405,  408,  408,  408,  408,  408,  408,  408,
      408,  408,  408,  408,  408,  408,  408,  408,  408,  408,
      408,  408,  408,  408,  408,  408,  408,  408,  408,  408,
      408,  408,  408,  408,  408,  408,  408,  408,  408,  408,

      408,  408,  408,  408,  408,  406,  406,  407,  407,  405,
      405,  405,  405,  405,  405,  415,  415,  405,  405,  405,
      405,  405,  408,  408,  408,  408,  408,  408,  408,  408,
      408,  408,  408,  408,  408,  408,  408,  408,  408,  408,
      408,  408,  408,  408,  408,  408,  408,  408,  408,  408,
      408,  408,  408,  408,  408,  408,  408,  408,  408,  408,
      408,  408,  408,  406,  207,  407,  209,  405,  405,  405,
      405,  405,  405,  405,  405,  408,  408,  408,  408,  408,
      408,  408,  408,  408,  408,  408,  408,  408,  408,  408,
      408,  408,  408,  408,  408,  408,  408,  408,  408,  408,

      408,  408,  408,  408,  408,  408,  408,  408,  405,  405,
      405,  405,  405,  405,  408,  408,  408,  408,  408,  408,
      408,  408,  408,  408,  408,  408,  408,  408,  408,  408,
      408,  408,  408,  408,  408,  408,  408,  408,  408,  408,
      405,  405,  408,  408,  408,  408,  408,  408,  408,  408,
      408,  408,  408,  408,  408,  408,  408,  408,  408,  408,
      408,  408,  405,  405,  408,  408,  408,  408,  408,  408,
      408,  408,  408,  408,  408,  408,  408,  408,  408,  408,
      408,  408,  408,  408,  408,  408,  408,  408,  408,  408,
      408,  408,  408,  408,  408,  408,  405,  405,  405,  416,

      416,  405,  405,  405,    0,  405,  405,  405,  405,  405,
      405,  405,  405,  405,  405,  405
    } ;

static const flex_int16_t yy_nxt[824] =
    {   0,
        4,    5,    6,    5,    7,    8,    9,   10,   11,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   21,   21,
       21,   22,   23,   24,   25,   26,   27,   28,   28,   28,
       28,   28,   28,   28,   28,   28,   29,   28,   28,   28,
       28,   29,   28,   30,    4,   31,   32,   33,   34,   35,
       36,   37,   38,   39,   40,   28,   41,   28,   42,   28,
       28,   28,   28,   43,   44,   45,   46,   47,   48,   28,
       28,   28,   49,   50,   51,   52,   53,   53,   53,   53,
       53,   53,   56,   58,   59,   60,   65,  402,   70,   67,
       71,   71,   71,   71,   93,   94,   72,  110,   66,   68,

       69,   73,   61,   96,  111,  113,   97,  402,  118,   74,
      112,  119,  121,   75,  114,   83,   83,   83,   83,  122,
      195,   57,   75,  134,   76,   76,   77,   77,   96,   78,
      115,   97,  116,  164,   84,   56,   88,  196,   78,   85,
      165,  117,  130,   79,  141,  125,  126,  173,   80,   81,
       78,   89,  174,   90,   91,  127,   86,   56,  128,   78,
       53,   53,   53,  396,   85,   82,  139,  139,  395,   99,
      100,  101,  135,   80,   57,  102,   81,  103,  154,  104,
       63,  105,  106,  131,  136,  136,  136,  160,   96,  107,
      142,  142,   71,   71,   71,   71,   57,  203,  394,  204,

      155,  188,   71,   71,   71,   71,  145,  146,  189,  161,
       75,  146,   76,   76,   77,   77,  148,  149,  140,  137,
      152,  149,  201,  153,  137,  153,   78,  145,  146,  158,
      202,   79,  403,  146,  159,  191,   80,  148,  149,  404,
      152,  393,  143,  149,  403,  192,  193,   78,  153,  138,
      153,  404,   75,   82,   77,   77,   77,   77,  150,  159,
      150,   80,  159,  151,  151,  151,  151,   75,   78,   83,
       83,   83,   83,   56,   56,  197,  136,  136,  136,  158,
       96,   96,  153,   78,  159,  206,  206,  159,   84,   78,
      198,  141,  274,   85,  392,  137,  151,  151,  151,  151,

      208,  208,  238,  239,   78,  391,  390,  153,  389,  159,
       86,  137,   57,   57,  275,  210,  137,  210,   85,  217,
      211,  211,  211,  211,  212,   56,  212,   63,  388,  213,
      213,  213,  213,  151,  151,  151,  151,  264,  264,  268,
      218,  138,  219,  269,  141,  220,  271,  343,  214,  387,
      141,  386,  214,  266,  266,  211,  211,  211,  211,  397,
      344,  385,  221,  268,   57,  398,  219,  269,  271,  214,
      220,  271,  384,  383,  214,   56,  211,  211,  211,  211,
       63,  213,  213,  213,  213,  270,   63,  265,  265,  265,
      265,  146,  382,  271,  381,  146,  380,  265,  265,  265,

      265,  265,  265,  273,  273,  273,  273,  310,  310,  310,
      310,  270,  146,  379,   57,  378,  271,  146,  265,  265,
      265,  265,  265,  265,  141,  312,  312,  312,  312,  377,
      376,  375,  374,  267,  267,  267,  267,  213,  213,  213,
      213,  271,  373,  267,  267,  267,  267,  267,  267,  363,
      363,  363,  149,  363,  363,  363,  149,  364,  372,  371,
       63,  364,  370,  369,  267,  267,  267,  267,  267,  267,
      368,  397,  367,  149,  272,  366,  272,  398,  149,  273,
      273,  273,  273,  309,  365,  309,  362,  399,  310,  310,
      310,  310,  311,  400,  311,  361,  360,  312,  312,  312,

      312,  273,  273,  273,  273,  399,  359,  310,  310,  310,
      310,  400,  358,  357,  356,  355,  313,  354,  353,  352,
      313,  351,  341,  350,  349,  348,  341,  347,  346,  345,
      312,  312,  312,  312,  340,  339,  338,  313,  337,  336,
      335,  334,  313,  341,  333,  342,  332,  331,  341,  342,
      330,  329,  328,  327,  326,  325,  324,  323,  322,  321,
      320,  319,  318,  317,  316,  315,  342,  314,  314,  308,
      307,  342,   55,  306,   55,   55,   55,   55,   55,   55,
       55,   62,  305,   62,  304,   62,   62,   62,   62,   62,
       95,   95,   95,   95,   55,   55,  303,   55,  302,  301,

       55,   62,   62,  300,   62,  299,  298,   62,  147,  297,
      147,  147,  147,  147,  147,  147,  147,  157,  157,  157,
      207,  207,  209,  209,  216,  216,  401,  401,  401,  401,
      401,  401,  401,  401,  401,  296,  295,  294,  293,  292,
      291,  290,  289,  288,  287,  286,  285,  284,  283,  282,
      281,  280,  279,  278,  277,  276,  263,  262,  261,  260,
      259,  258,  257,  256,  255,  254,  253,  252,  251,  250,
      249,  248,  247,  246,  245,  244,  243,  242,  241,  240,
      237,  236,  235,  234,  233,  232,  231,  230,  229,  228,
      227,  226,  225,  224,  223,  222,  222,  215,  215,   96,

      205,   96,  200,  199,  194,  190,  187,  186,  185,  184,
      183,  182,  181,  180,  179,  178,  177,  176,  175,  172,
      171,  170,  169,  168,  167,  166,   63,  163,  162,  156,
      144,  133,  132,  129,  124,  123,  120,  109,  108,   98,
       92,   87,   64,   63,   54,  405,    3,  405,  405,  405,
      405,  405,  405,  405,  405,  405,  405,  405,  405,  405,
      405,  405,  405,  405,  405,  405,  405,  405,  405,  405,
      405,  405,  405,  405,  405,  405,  405,  405,  405,  405,
      405,  405,  405,  405,  405,  405,  405,  405,  405,  405,
      405,  405,  405,  405,  405,  405,  405,  405,  405,  405,

      405,  405,  405,  405,  405,  405,  405,  405,  405,  405,
      405,  405,  405,  405,  405,  405,  405,  405,  405,  405,
      405,  405,  405
    } ;

static const flex_int16_t yy_chk[824] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    5,    5,    5,    6,
        6,    6,    8,    9,    9,   10,   15,  401,   18,   17,
       18,   18,   18,   18,   26,   26,   19,   36,   15,   17,

       17,   19,   10,   29,   36,   37,   29,  400,   39,   19,
       36,   39,   41,   21,   37,   21,   21,   21,   21,   41,
      126,    8,   20,   50,   20,   20,   20,   20,   46,   21,
       38,   46,   38,   99,   21,   55,   24,  126,   20,   21,
       99,   38,   46,   20,   62,   44,   44,  107,   20,   20,
       21,   24,  107,   24,   24,   44,   21,   96,   44,   20,
       53,   53,   53,  393,   21,   20,   57,   57,  392,   33,
       33,   33,   50,   20,   55,   33,   20,   33,   80,   33,
       62,   33,   33,   46,   56,   56,   56,   85,   56,   33,
       63,   63,   71,   71,   71,   71,   96,  132,  391,  132,

       80,  122,   75,   75,   75,   75,   71,   71,  122,   85,
       76,   71,   76,   76,   76,   76,   75,   75,   57,   56,
       79,   75,  131,   82,   56,   79,   76,   71,   71,   84,
      131,   76,  402,   71,   84,  124,   76,   75,   75,  402,
       82,  390,   63,   75,  403,  124,  124,   76,   82,   56,
       79,  403,   77,   76,   77,   77,   77,   77,   78,   84,
       78,   76,   86,   78,   78,   78,   78,   83,   77,   83,
       83,   83,   83,  139,  264,  127,  136,  136,  136,   86,
      136,  138,  152,   83,  158,  139,  139,   86,   83,   77,
      127,  142,  220,   83,  389,  138,  150,  150,  150,  150,

      142,  142,  179,  179,   83,  388,  387,  152,  386,  158,
       83,  136,  139,  264,  220,  145,  136,  145,   83,  157,
      145,  145,  145,  145,  148,  206,  148,  142,  385,  148,
      148,  148,  148,  151,  151,  151,  151,  206,  206,  216,
      157,  136,  157,  217,  208,  157,  270,  315,  151,  384,
      266,  382,  151,  208,  208,  210,  210,  210,  210,  395,
      315,  381,  157,  216,  206,  395,  157,  217,  221,  151,
      157,  270,  380,  378,  151,  207,  211,  211,  211,  211,
      208,  212,  212,  212,  212,  221,  266,  207,  207,  207,
      207,  211,  371,  221,  370,  211,  369,  207,  207,  207,

      207,  207,  207,  272,  272,  272,  272,  309,  309,  309,
      309,  218,  211,  368,  207,  367,  218,  211,  207,  207,
      207,  207,  207,  207,  209,  311,  311,  311,  311,  360,
      359,  357,  356,  209,  209,  209,  209,  213,  213,  213,
      213,  218,  354,  209,  209,  209,  209,  209,  209,  345,
      345,  345,  213,  363,  363,  363,  213,  345,  353,  352,
      209,  363,  351,  350,  209,  209,  209,  209,  209,  209,
      349,  397,  348,  213,  219,  347,  219,  397,  213,  219,
      219,  219,  219,  268,  346,  268,  344,  398,  268,  268,
      268,  268,  269,  398,  269,  343,  340,  269,  269,  269,

      269,  273,  273,  273,  273,  399,  339,  310,  310,  310,
      310,  399,  338,  331,  330,  326,  273,  325,  324,  323,
      273,  322,  310,  321,  320,  319,  310,  318,  317,  316,
      312,  312,  312,  312,  307,  306,  304,  273,  303,  302,
      301,  300,  273,  310,  299,  312,  297,  296,  310,  312,
      295,  294,  292,  291,  290,  289,  286,  285,  284,  283,
      282,  281,  280,  279,  277,  276,  312,  275,  274,  263,
      262,  312,  406,  260,  406,  406,  406,  406,  406,  406,
      406,  407,  259,  407,  258,  407,  407,  407,  407,  407,
      408,  408,  408,  408,  409,  409,  257,  409,  256,  255,

      409,  410,  410,  254,  410,  253,  252,  410,  411,  251,
      411,  411,  411,  411,  411,  411,  411,  412,  412,  412,
      413,  413,  414,  414,  415,  415,  416,  416,  416,  416,
      416,  416,  416,  416,  416,  250,  249,  247,  245,  244,
      241,  240,  239,  238,  235,  233,  232,  231,  230,  229,
      228,  227,  226,  225,  224,  223,  205,  204,  203,  202,
      201,  200,  199,  198,  197,  196,  195,  194,  193,  192,
      191,  190,  188,  187,  185,  184,  183,  182,  181,  180,
      178,  177,  176,  175,  174,  173,  172,  171,  170,  169,
      168,  167,  166,  165,  164,  161,  160,  155,  154,  137,

      133,  130,  129,  128,  125,  123,  120,  119,  118,  117,
      116,  115,  114,  113,  112,  111,  110,  109,  108,  106,
      105,  104,  103,  102,  101,  100,   97,   94,   90,   81,
       70,   48,   47,   45,   43,   42,   40,   35,   34,   32,
       25,   22,   14,   11,    7,    3,  405,  405,  405,  405,
      405,  405,  405,  405,  405,  405,  405,  405,  405,  405,
      405,  405,  405,  405,  405,  405,  405,  405,  405,  405,
      405,  405,  405,  405,  405,  405,  405,  405,  405,  405,
      405,  405,  405,  405,  405,  405,  405,  405,  405,  405,
      405,  405,  405,  405,  405,  405,  405,  405,  405,  405,

      405,  405,  405,  405,  405,  405,  405,  405,  405,  405,
      405,  405,  405,  405,  405,  405,  405,  405,  405,  405,
      405,  405,  405
    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[111] =
    {   0,
0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "C_grammar.l"
/****************************************************************************************************/
/* C11 lexer file from https://www.quut.com/c/ANSI-C-grammar-l-2011.html                            */
/* Flex documentation: https://westes.github.io/flex/manual/index.html                        */
/****************************************************************************************************/
/* definition section */
#line 16 "C_grammar.l"
#ifdef _MSC_VER
    #define strdup_safe(char_ptr) _strdup(char_ptr)
#else
    #define strdup_safe(char_ptr) strdup(char_ptr)
#endif

#include <stdio.h>
#include <limits.h>

#include "C_grammar.tab.h"

extern int is_typedef_name(char*);

void read_comment();
int differentiate_identifiers(char *);
void wrap_integer_constants(char *, char *, char **);
void wrap_floating_point_constants(char *, char *, char **);
void add_missing_zero(char *, char **);
#line 815 "lex.yy.c"
#line 816 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 52 "C_grammar.l"

#line 54 "C_grammar.l"
        /* rules section */
#line 1037 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 406 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 747 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 55 "C_grammar.l"
{ read_comment(); }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 56 "C_grammar.l"
{ /* consume //-comment */ }
	YY_BREAK
case 3:
/* rule 3 can match eol */
YY_RULE_SETUP
#line 58 "C_grammar.l"
{ /* Pattern to ignore GCC __attribute__ */ }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 60 "C_grammar.l"
{ return(AUTO); }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 61 "C_grammar.l"
{ return(BREAK); }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 62 "C_grammar.l"
{ return(CASE); }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 63 "C_grammar.l"
{ return(CHAR); }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 64 "C_grammar.l"
{ return(CONST); }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 65 "C_grammar.l"
{ return(CONTINUE); }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 66 "C_grammar.l"
{ return(DEFAULT); }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 67 "C_grammar.l"
{ return(DO); }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 68 "C_grammar.l"
{ return(DOUBLE); }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 69 "C_grammar.l"
{ return(ELSE); }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 70 "C_grammar.l"
{ return(ENUM); }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 71 "C_grammar.l"
{ return(EXTERN); }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 72 "C_grammar.l"
{ return(FLOAT); }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 73 "C_grammar.l"
{ return(FOR); }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 74 "C_grammar.l"
{ return(GOTO); }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 75 "C_grammar.l"
{ return(IF); }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 76 "C_grammar.l"
{ return(INLINE); }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 77 "C_grammar.l"
{ return(INT); }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 78 "C_grammar.l"
{ return(LONG); }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 79 "C_grammar.l"
{ return(REGISTER); }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 80 "C_grammar.l"
{ return(RESTRICT); }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 81 "C_grammar.l"
{ return(RETURN); }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 82 "C_grammar.l"
{ return(SHORT); }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 83 "C_grammar.l"
{ return(SIGNED); }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 84 "C_grammar.l"
{ return(SIZEOF); }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 85 "C_grammar.l"
{ return(STATIC); }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 86 "C_grammar.l"
{ return(STRUCT); }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 87 "C_grammar.l"
{ return(SWITCH); }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 88 "C_grammar.l"
{ return(TYPEDEF); }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 89 "C_grammar.l"
{ return(UNION); }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 90 "C_grammar.l"
{ return(UNSIGNED); }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 91 "C_grammar.l"
{ return(VOID); }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 92 "C_grammar.l"
{ return(VOLATILE); }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 93 "C_grammar.l"
{ return(WHILE); }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 94 "C_grammar.l"
{ return ALIGNAS; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 95 "C_grammar.l"
{ return ALIGNOF; }
	YY_BREAK
case 40:
/* rule 40 can match eol */
YY_RULE_SETUP
#line 96 "C_grammar.l"
{ return ATOMIC_SPECIFIER; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 97 "C_grammar.l"
{ return ATOMIC; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 98 "C_grammar.l"
{ return BOOL; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 99 "C_grammar.l"
{ return COMPLEX; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 100 "C_grammar.l"
{ return GENERIC; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 101 "C_grammar.l"
{ return IMAGINARY; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 102 "C_grammar.l"
{ return NORETURN; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 103 "C_grammar.l"
{ return STATIC_ASSERT; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 104 "C_grammar.l"
{ return THREAD_LOCAL; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 105 "C_grammar.l"
{ return FUNC_NAME; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 107 "C_grammar.l"
{yylval.id = strdup_safe(yytext);
                              if (is_typedef_name(yylval.id)) {
                                  return TYPEDEF_NAME;
                              }
                              return IDENTIFIER;
                            }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 114 "C_grammar.l"
{wrap_integer_constants("hexadecimal", yytext, &yylval.id);
                             return I_CONSTANT;
                            }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 117 "C_grammar.l"
{wrap_integer_constants("", yytext, &yylval.id);
                             return I_CONSTANT;
                            }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 121 "C_grammar.l"
{if (strcmp(yytext, "0")) wrap_integer_constants("octal", yytext, &yylval.id);
                             else wrap_integer_constants("", yytext, &yylval.id);   //because it's just the constant 0, not an octal
                             return I_CONSTANT;
                            }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 125 "C_grammar.l"
{yylval.id = strdup_safe(yytext); return I_CONSTANT;}   //single characters
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 127 "C_grammar.l"
{wrap_floating_point_constants("", yytext, &yylval.id);     //Decimal floating-point constants with an exponent.
                             return F_CONSTANT;
                            }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 130 "C_grammar.l"
{wrap_floating_point_constants("", yytext, &yylval.id);     //Decimal floating-point constants with a fractional part.
                             return F_CONSTANT;
                            }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 133 "C_grammar.l"
{char* added_0;
                             add_missing_zero(yytext, &added_0);
                             wrap_floating_point_constants("", added_0, &yylval.id);         //Decimal floating-point constants with a fractional part.
                             return F_CONSTANT;
                            }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 138 "C_grammar.l"
{wrap_floating_point_constants("hexadecimal", yytext, &yylval.id);  //Hexadecimal floating-point constants
                             return F_CONSTANT;
                            }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 141 "C_grammar.l"
{wrap_floating_point_constants("hexadecimal", yytext, &yylval.id);    //Hexadecimal floating-point constants with a fractional part.
                             return F_CONSTANT;
                            }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 144 "C_grammar.l"
{char* added_0;
                             add_missing_zero(yytext, &added_0);
                             wrap_floating_point_constants("hexadecimal", added_0, &yylval.id);   //Hexadecimal floating-point constants with digits before the decimal point, but none after.
                             return F_CONSTANT;
                            }
	YY_BREAK
case 61:
/* rule 61 can match eol */
YY_RULE_SETUP
#line 150 "C_grammar.l"
{if (yytext[0] == 'L') { //a wide string constant
                                        size_t const size = strlen("wide_string()") + strlen(yytext) - 1 + 1;
                                        yylval.id = (char*)malloc(size);
                                        sprintf_safe(yylval.id, size, "wide_string(%s)", &yytext[1]);      //copy from yytext[1] to remove 'L' prefix 
                                     } else {
                                        yylval.id = strdup_safe(yytext);
                                     }
                                     return STRING_LITERAL;
                                    }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 160 "C_grammar.l"
{ return ELLIPSIS; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 161 "C_grammar.l"
{ return RIGHT_ASSIGN; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 162 "C_grammar.l"
{ return LEFT_ASSIGN; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 163 "C_grammar.l"
{ return ADD_ASSIGN; }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 164 "C_grammar.l"
{ return SUB_ASSIGN; }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 165 "C_grammar.l"
{ return MUL_ASSIGN; }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 166 "C_grammar.l"
{ return DIV_ASSIGN; }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 167 "C_grammar.l"
{ return MOD_ASSIGN; }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 168 "C_grammar.l"
{ return AND_ASSIGN; }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 169 "C_grammar.l"
{ return XOR_ASSIGN; }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 170 "C_grammar.l"
{ return OR_ASSIGN; }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 171 "C_grammar.l"
{ return RIGHT_OP; }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 172 "C_grammar.l"
{ return LEFT_OP; }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 173 "C_grammar.l"
{ return INC_OP; }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 174 "C_grammar.l"
{ return DEC_OP; }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 175 "C_grammar.l"
{ return PTR_OP; }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 176 "C_grammar.l"
{ return AND_OP; }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 177 "C_grammar.l"
{ return OR_OP; }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 178 "C_grammar.l"
{ return LE_OP; }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 179 "C_grammar.l"
{ return GE_OP; }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 180 "C_grammar.l"
{ return EQ_OP; }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 181 "C_grammar.l"
{ return NE_OP; }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 182 "C_grammar.l"
{ return ';'; }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 183 "C_grammar.l"
{ return '{'; }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 184 "C_grammar.l"
{ return '}'; }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 185 "C_grammar.l"
{ return ','; }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 186 "C_grammar.l"
{ return ':'; }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 187 "C_grammar.l"
{ return '='; }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 188 "C_grammar.l"
{ return '('; }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 189 "C_grammar.l"
{ return ')'; }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 190 "C_grammar.l"
{ return '['; }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 191 "C_grammar.l"
{ return ']'; }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 192 "C_grammar.l"
{ return '.'; }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 193 "C_grammar.l"
{ return '&'; }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 194 "C_grammar.l"
{ return '!'; }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 195 "C_grammar.l"
{ return '~'; }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 196 "C_grammar.l"
{ return '-'; }
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 197 "C_grammar.l"
{ return '+'; }
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 198 "C_grammar.l"
{ return '*'; }
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 199 "C_grammar.l"
{ return '/'; }
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 200 "C_grammar.l"
{ return '%'; }
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 201 "C_grammar.l"
{ return '<'; }
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 202 "C_grammar.l"
{ return '>'; }
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 203 "C_grammar.l"
{ return '^'; }
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 204 "C_grammar.l"
{ return '|'; }
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 205 "C_grammar.l"
{ return '?'; }
	YY_BREAK
case 108:
/* rule 108 can match eol */
YY_RULE_SETUP
#line 207 "C_grammar.l"
{ /* whitespace separates tokens */ }
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 208 "C_grammar.l"
{ /* discard bad characters */ }
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 210 "C_grammar.l"
ECHO;
	YY_BREAK
#line 1694 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 406 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 406 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 405);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 210 "C_grammar.l"

/* user code section */
int yywrap(void)        /* called at end of input */
{
    return 1;           /* terminate now */
}

void read_comment() {
    int c;

    while ((c = input()) != 0)
        if (c == '*')
        {
            while ((c = input()) == '*')
                ;

            if (c == '/')
                return;

            if (c == 0)
                break;
        }
}

//add hexademical or octal wrapper and handle u|l|ll variations
void wrap_integer_constants(char * wrapper, char * input, char ** output) {
    int current = strlen(input)-1;
    int has_u = 0, has_l = 0, has_ll = 0;
    int has_suffix = 1;

    while (has_suffix && current >= 0) {
        switch (input[current]) {
            case 'u':
            case 'U':
                has_u = 1;
                break;
            case 'l':
            case 'L':
                if (current >0 && (input[current-1] == 'l' || input[current-1] == 'L')) {
                    has_ll = 1;
                    current--;  //skip the other 'l' or 'LL'
                }
                else has_l = 1;
                break;
            default:
                has_suffix = 0;  
        }
        if (has_suffix) current--;
    }
    int has_wrapper = strcmp(wrapper, "");
    //calculating the length of the result: length of the wrapper + 2 parentheses + length of the prefix, the suffix, the underscore, the parenthesis
    int size = (has_wrapper ? strlen(wrapper) + 2 : 0) + current+1 + 1 + has_u*strlen("unsigned") + has_l*strlen("long") + has_ll*strlen("long_long") + has_u*has_l + has_u*has_ll + (has_u || has_l || has_ll ? 2 : 0);

    char format_string[100];

    if (has_wrapper) strcpy(format_string, "%s("); //starts with the integer kind wrapper
    else strcpy(format_string, "");

    if (!has_u && !has_l && !has_ll) {              //has no suffix, type depends on value
        unsigned long constant = strtoul(input, NULL, 0);         //the 0 enables automatic detection of base: decimal, octal or hexadecimal
        if (constant <= INT_MAX) {
            strcat(format_string, "int(%.*s)");
            size += 5;
        } else if (has_wrapper && constant <= UINT_MAX) {   //different rule for octals and hexademcimals
            strcat(format_string, "unsigned(%.*s)");
            size += strlen("unsigned()");
        }
         else if (constant <= 2147483647L) {          //don't use LONG_MAX, todo this should be dependent on the target compilation machine size (32 vs 64 bits) for the program under test
            strcat(format_string, "long(%.*s)");
            size += 6;
        } else {
            strcat(format_string, "unsigned_long(%.*s)");
            size += strlen("unsigned_long()");
        }   
    }
    else if (has_u && !has_l && !has_ll) 
        strcat(format_string, "unsigned(%.*s)");
    else if (has_u && has_l && !has_ll) 
        strcat(format_string, "unsigned_long(%.*s)");
    else if (has_u && !has_l && has_ll) 
        strcat(format_string, "unsigned_long_long(%.*s)");
    else if (!has_u && has_l && !has_ll) 
        strcat(format_string, "long(%.*s)");
    else if (!has_u && !has_l && has_ll) 
        strcat(format_string, "long_long(%.*s)");
     
    *output = (char *)malloc(size);
    if (has_wrapper) {
        strcat(format_string, ")"); //adds the wrapper end parenthesis
        snprintf(*output, size, format_string, wrapper, current + 1, input);
    } else {
        snprintf(*output, size, format_string, current + 1, input);
    }
}

//add hexademical wrapper if present and handle f|F|l|L variations
void wrap_floating_point_constants(char * wrapper, char * input, char ** output) {
    int current = strlen(input)-1;
    int has_f = 0, has_l = 0, is_d = 0;
    int has_suffix = 1;
    switch (input[current]) {
        case 'f':
        case 'F':
            has_f = 1;
            break;
        case 'l':
        case 'L':
            has_l = 1;
            break;
        default:
            is_d = 1;
            has_suffix = 0;
    }
    if (has_suffix) current--;
    int has_wrapper = strcmp(wrapper, "");
    //calculating the length of the result: length of the wrapper + 2 parentheses + length of the prefix, the suffix, the parenthesis
    int size = (has_wrapper ? strlen(wrapper) + 2 : 0) + current+1 + 1 + is_d*strlen("double") + has_f*strlen("float") + has_l*strlen("long_double") + (has_f || has_l || is_d ? 2 : 0);
    *output = (char *)malloc(size);
    char format_string[100];
    if (has_wrapper) strcpy(format_string, "%s("); //starts with the floating point kind wrapper
    else strcpy(format_string, "");
    if (is_d)
        strcat(format_string, "double(%.*s)");      //double is the default type for floating points literals
    else if (has_f) 
        strcat(format_string, "float(%.*s)");
    else if (has_l) 
        strcat(format_string, "long_double(%.*s)");
    if (has_wrapper) {
        strcat(format_string, ")"); //adds the wrapper end parenthesis
        snprintf(*output, size, format_string, wrapper, current + 1, input);
    } else {
        snprintf(*output, size, format_string, current + 1, input);
    }
}

//float has no digit after decimal point: need to add 0
void add_missing_zero(char * input, char ** output) {
    size_t len = strlen(input);
    *output = (char*)malloc(len + 1 + 1); // +1 for extra '0'
    strcpy(*output, input);
    char* decimal_point = strchr(*output, '.');
    char* suffix = strpbrk(decimal_point, "eElL"); //returns pointer to first occurrence of character
    if (suffix == NULL) {// No suffix, so it's the end of the string
        suffix = *output + strlen(*output);
    }
    size_t decimal_pos = decimal_point - *output;
    memmove(decimal_point + 2, decimal_point + 1, len - decimal_pos); //copy everything after the decimal point to +1 location
    (*output)[decimal_pos + 1] = '0';    //add the 'missing' 0
}
