
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 119
#define YY_END_OF_BUFFER 120
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[482] =
    {   0,
        0,    0,    0,    0,  120,  118,  117,  117,  105,  118,
      118,  111,  104,  118,   99,  100,  109,  108,   96,  107,
      103,  110,   62,   61,   97,   93,  112,   98,  113,  116,
       59,   59,  101,  102,  114,   59,   59,   59,   59,   59,
       59,   59,   59,   59,   59,   59,   59,   59,   59,   59,
       59,   94,  115,   95,  106,    6,  119,  117,   92,    0,
       70,    0,    0,   78,   95,   87,   79,    0,    0,   76,
       84,   74,   85,   75,   86,    0,   65,    1,    2,   77,
       66,   62,    0,    0,   62,   62,    0,   62,   61,   61,
       61,   61,  102,   94,  101,   83,   89,   91,   90,   82,

       59,    0,    0,   80,   59,   59,   59,   59,   59,   59,
       59,   59,   59,   59,   59,   59,   59,   59,   59,   14,
       59,   59,   59,   59,   59,   59,   22,   59,   59,   59,
       59,   59,   59,   59,   59,   59,   59,   59,   59,   81,
       88,   70,    0,    0,    0,    0,    0,   63,    0,    0,
       71,    0,   65,    2,    0,   66,    0,   64,   62,   62,
       62,   62,    0,   60,   61,   61,   61,   61,   73,   72,
       59,   59,   59,   59,   59,   59,   59,   59,   59,   59,
       59,   59,   59,   59,   59,   59,   59,   59,   59,   59,
       59,   59,   59,   59,   59,   59,   59,   20,   59,   59,

       25,   59,   59,   59,   59,   59,   59,   59,   59,   59,
       59,   59,   59,   59,   59,   59,   59,    0,    0,    0,
        0,    0,    0,   65,    0,   66,   64,   62,    0,    0,
       60,    0,   60,   60,   61,   59,   59,   59,   59,   59,
       59,   59,   59,   59,   59,   59,   59,   59,   59,   59,
       59,   59,    7,   59,    9,   10,   59,   59,   59,   59,
       16,   17,   59,   59,   21,   59,   26,   59,   59,   59,
       59,   59,   59,   59,   59,   59,   59,   59,   59,   40,
       59,   59,    0,    0,    0,    0,    0,    0,    0,   60,
       60,    0,   67,   60,   60,   59,   59,   50,   59,   59,

       59,   59,   59,   59,   59,   59,   59,   59,   59,   59,
       59,   59,   59,    8,   11,   59,   59,   59,   59,   19,
       59,   59,   59,   59,   31,   59,   59,   59,   59,   59,
       59,   38,   59,   59,   42,    0,    0,   68,    0,   69,
       67,   60,   59,   59,   59,   59,   59,   59,   59,   59,
       59,   59,   59,   59,   59,   59,   59,   59,   59,   59,
       59,   15,   18,   23,   59,   59,   30,   32,   33,   34,
       35,   36,   59,   59,   59,    3,   68,   69,   59,   59,
       49,   59,   59,   59,   59,   59,   59,   59,   59,   59,
       59,   59,   59,   59,   59,   59,   59,   13,   59,   59,

       37,   59,   59,    3,   46,   47,    0,   48,   51,   52,
       59,   59,   59,   59,   59,   59,   59,   59,   59,   58,
       24,   43,   59,   12,   27,   28,   39,   41,   59,   54,
       59,   59,   59,   59,   59,   59,   59,   59,   53,   59,
       59,   59,   59,   59,   59,   44,   29,   59,   59,   59,
       59,   59,   59,   59,   59,   59,   59,   59,   59,   59,
       56,   59,   59,   59,    4,   55,   59,    0,    0,   59,
       59,    0,    5,   59,   59,   59,   59,   45,   59,   57,
        0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        2,    2,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    7,    1,    8,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   21,
       22,   22,   22,   22,   22,   23,   24,   25,   26,   27,
       28,   29,   30,    1,   31,   32,   33,   34,   35,   36,
       37,   38,   39,   38,   38,   40,   38,   41,   42,   43,
       38,   44,   45,   46,   47,   38,   38,   48,   49,   38,
       50,   51,   52,   53,   54,    1,   55,   56,   57,   58,

       59,   60,   61,   62,   63,   38,   64,   65,   66,   67,
       68,   69,   38,   70,   71,   72,   73,   74,   75,   76,
       77,   78,   79,   80,   81,   82,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[83] =
    {   0,
        1,    1,    2,    1,    1,    3,    1,    1,    1,    4,
        1,    1,    1,    1,    1,    1,    5,    1,    6,    6,
        6,    6,    7,    7,    1,    1,    1,    1,    1,    3,
        7,    7,    7,    7,    7,    7,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    1,
        3,    1,    1,    8,    6,    6,    7,    7,    7,    6,
        8,    8,    8,    8,    8,    8,    9,    8,    8,    9,
        8,    9,    8,    9,    8,    9,    8,    8,    1,    1,
        1,    1
    } ;

static const flex_int16_t yy_base[494] =
    {   0,
        0,    0,  871,  870,  872,  875,   81,   84,  843,   83,
      801,   62,   83,  818,  875,  875,  840,   79,  875,   80,
       78,   92,  118,  178,  838,  875,   96,  838,   84,  875,
        0,  108,  875,  875,  837,  115,  791,  793,   60,   35,
       60,   51,  794,   66,  793,  801,   87,  782,  145,  790,
      795,  875,  101,  875,  875,  875,  875,  128,  875,  137,
      168,  184,  786,  875,  875,  875,  875,  134,  200,  875,
      875,  875,  875,  875,  875,  838,  209,  875,    0,  875,
      235,   69,  261,  283,  117,  127,  837,  162,    0,  167,
      146,  169,  875,  875,  875,  825,  875,  875,  875,  824,

        0,  172,  800,  875,  108,  782,  781,  789,  781,  778,
      773,  782,  255,  771,  783,  770,  785,  772,  778,  764,
      765,  762,  762,  765,  762,  759,    0,  110,  763,  175,
      761,  115,  169,  765,  758,  820,  116,  185,  762,  875,
      875,  261,  818,  256,  271,    0,  768,  875,  307,    0,
      875,  316,  875,    0,  327,  875,  333,  340,  116,  875,
      782,  756,    0,  325,  137,  875,  780,  754,  875,  875,
      755,  749,  748,  749,  747,  758,  742,  756,  740,  765,
      736,  734,  730,  188,  738,  745,  735,  747,  742,  730,
      201,  744,  742,  738,  730,  736,  739,    0,  725,  729,

        0,  730,  727,  717,  715,  717,  719,  726,  712,  710,
      710,  722,  712,  716,  720,  722,  711,  363,  409,  714,
      367,  460,  387,  466,  400,  513,  875,  875,  183,  243,
      326,  432,  248,  328,  875,  713,  707,  707,  702,  711,
      708,  709,  695,  707,  730,  692,  700,  690,  693,  693,
      244,  688,    0,  694,    0,    0,  685,  693,  682,  689,
        0,    0,  683,  680,    0,  684,    0,  679,  679,  678,
      675,  687,  677,  681,  686,  685,  683,  673,  678,    0,
      666,  678,  327,    0,  670,  361,    0,  524,  536,  272,
      875,  415,  543,  695,  669,  666,  669,    0,  666,  660,

      666,  649,  640,  645,  653,  627,  628,  633,  635,  621,
      613,  647,  583,    0,    0,  587,  588,  593,  583,    0,
      590,  576,  584,  579,    0,  587,  584,  586,  570,  579,
      581,    0,  572,  575,    0,  582,  452,  565,  571,  591,
      875,  875,  276,  579,  576,  571,  566,  559,  572,  570,
      580,  561,  551,  555,  549,  566,  552,  597,  547,  543,
      537,    0,    0,    0,  548,  549,    0,    0,    0,    0,
        0,    0,  544,  543,  535,    0,  875,  875,  528,  538,
      393,  521,  539,  527,  511,  526,  523,  527,  519,  511,
      501,  551,  516,  510,  545,  498,  495,    0,  481,  470,

        0,  483,  480,    0,    0,    0,  496,  875,    0,    0,
      460,  462,  473,  462,  471,  451,  456,  459,  500,    0,
        0,    0,  457,    0,    0,    0,    0,    0,  436,    0,
      441,  442,  473,  433,  449,  410,  454,  391,    0,  391,
      404,  412,  399,  375,  380,    0,    0,  368,  371,  384,
      363,  361,  359,  333,  337,  359,  337,  327,  325,  298,
        0,  278,  363,  258,    0,    0,  282,  446,  493,  226,
      245,  497,  875,  195,  197,  145,  142,    0,   52,    0,
      875,  656,  665,  674,  678,  685,  692,  701,  706,  708,
      710,  712,  719

    } ;

static const flex_int16_t yy_def[494] =
    {   0,
      481,    1,  482,  482,  481,  481,  481,  481,  481,  483,
      481,  481,  481,  484,  481,  481,  481,  481,  481,  481,
      481,  481,  481,  481,  481,  481,  481,  481,  481,  481,
      485,  485,  481,  481,  481,  485,  485,  485,  485,  485,
      485,  485,  485,  485,  485,  485,  485,  485,  485,  485,
      485,  481,  481,  481,  481,  481,  481,  481,  481,  483,
      481,  486,  481,  481,  481,  481,  481,  484,  487,  481,
      481,  481,  481,  481,  481,  481,  481,  481,  488,  481,
      481,   23,  481,  481,  481,  481,  489,  481,   24,  481,
      481,  481,  481,  481,  481,  481,  481,  481,  481,  481,

      485,  483,  484,  481,  485,  485,  485,  485,  485,  485,
      485,  485,  485,  485,  485,  485,  485,  485,  485,  485,
      485,  485,  485,  485,  485,  485,  485,  485,  485,  485,
      485,  485,  485,  485,  485,  485,  485,  485,  485,  481,
      481,  481,  481,  481,  483,  490,  481,  481,  484,  491,
      481,  481,  481,  488,  481,  481,  481,  481,  481,  481,
      481,  481,  492,  489,  481,  481,  481,  481,  481,  481,
      485,  485,  485,  485,  485,  485,  485,  485,  485,  485,
      485,  485,  485,  485,  485,  485,  485,  485,  485,  485,
      485,  485,  485,  485,  485,  485,  485,  485,  485,  485,

      485,  485,  485,  485,  485,  485,  485,  485,  485,  485,
      485,  485,  485,  485,  485,  485,  485,  483,  483,  481,
      484,  484,  481,  481,  481,  481,  481,  481,  492,  492,
      481,  481,  481,  481,  481,  485,  485,  485,  485,  485,
      485,  485,  485,  485,  485,  485,  485,  485,  485,  485,
      485,  485,  485,  485,  485,  485,  485,  485,  485,  485,
      485,  485,  485,  485,  485,  485,  485,  485,  485,  485,
      485,  485,  485,  485,  485,  485,  485,  485,  485,  485,
      485,  485,  483,  219,  481,  484,  222,  481,  481,  481,
      481,  481,  481,  481,  481,  485,  485,  485,  485,  485,

      485,  485,  485,  485,  485,  485,  485,  485,  485,  485,
      485,  485,  485,  485,  485,  485,  485,  485,  485,  485,
      485,  485,  485,  485,  485,  485,  485,  485,  485,  485,
      485,  485,  485,  485,  485,  481,  481,  481,  481,  481,
      481,  481,  485,  485,  485,  485,  485,  485,  485,  485,
      485,  485,  485,  485,  485,  485,  485,  485,  485,  485,
      485,  485,  485,  485,  485,  485,  485,  485,  485,  485,
      485,  485,  485,  485,  485,  493,  481,  481,  485,  485,
      485,  485,  485,  485,  485,  485,  485,  485,  485,  485,
      485,  485,  485,  485,  485,  485,  485,  485,  485,  485,

      485,  485,  485,  493,  485,  485,  481,  481,  485,  485,
      485,  485,  485,  485,  485,  485,  485,  485,  485,  485,
      485,  485,  485,  485,  485,  485,  485,  485,  485,  485,
      485,  485,  485,  485,  485,  485,  485,  485,  485,  485,
      485,  485,  485,  485,  485,  485,  485,  485,  485,  485,
      485,  485,  485,  485,  485,  485,  485,  485,  485,  485,
      485,  485,  485,  485,  485,  485,  485,  481,  481,  485,
      485,  481,  481,  485,  485,  485,  485,  485,  485,  485,
        0,  481,  481,  481,  481,  481,  481,  481,  481,  481,
      481,  481,  481

    } ;

static const flex_int16_t yy_nxt[958] =
    {   0,
        6,    7,    8,    7,    9,   10,   11,   12,   13,   14,
       15,   16,   17,   18,   19,   20,   21,   22,   23,   24,
       24,   24,   24,   24,   25,   26,   27,   28,   29,   30,
       31,   31,   31,   31,   31,   31,   31,   31,   31,   32,
       31,   31,   31,   31,   31,   31,   32,   31,   31,   33,
        6,   34,   35,   36,   37,   38,   39,   40,   41,   42,
       43,   31,   44,   31,   45,   31,   31,   31,   31,   46,
       47,   48,   49,   50,   51,   31,   31,   31,   52,   53,
       54,   55,   58,   58,   58,   58,   58,   58,   61,   64,
       65,   66,   71,  119,   76,   73,   77,   77,   77,   77,

       77,   77,  120,   94,   78,  480,   72,   74,   75,   79,
       67,   99,  100,  102,  116,  124,  481,  103,  125,   80,
       95,  117,   96,   97,  121,  127,  122,  118,  140,   58,
       58,   58,  128,   62,   81,  123,   82,   82,   82,   82,
       83,   83,   61,  148,  481,  105,  106,  107,  131,  132,
      102,  108,   84,  109,  103,  110,  159,   85,  133,  111,
      112,  134,  160,  160,   86,   87,  161,  136,  113,  142,
      142,  142,  171,  102,  200,  207,   84,   61,  213,  172,
      141,  201,   88,  166,   69,  167,  214,   62,  160,  160,
       86,  162,  208,   87,   81,  479,   89,   89,   89,   89,

       89,   89,  145,  145,  145,  145,  165,  143,  160,  166,
      168,  137,   84,  166,  143,  166,  478,   90,  149,  149,
      149,  149,   62,  209,   91,  288,  159,   77,   77,   77,
       77,   77,   77,  165,  160,  203,   84,  477,  210,  166,
      144,  166,   92,  152,  153,  204,  205,  215,  153,  216,
       91,  288,  249,   77,   77,   77,   77,   77,   77,  146,
      250,  102,  142,  142,  142,  476,  102,  152,  153,  155,
      156,  257,  258,  153,  156,  150,   61,   81,  143,   83,
       83,   83,   83,   83,   83,  289,  475,  294,  474,  218,
      218,  218,  218,  155,  156,   84,  157,  180,  157,  156,

      143,  158,  158,  158,  158,  158,  158,  143,  311,  181,
      182,  289,  295,  183,  184,  312,  148,  185,  291,   84,
      471,   62,  470,  467,  186,  221,  221,  221,  221,  223,
      379,  223,   61,  144,  224,  224,  224,  224,  224,  224,
      225,  230,  225,  380,  291,  226,  226,  226,  226,  226,
      226,  158,  158,  158,  158,  158,  158,   69,  158,  158,
      158,  158,  158,  158,  231,  290,  468,  232,   61,  466,
      148,  233,  291,  469,  291,  227,  148,   62,  465,  227,
      464,  283,  283,  283,  283,  286,  286,  286,  286,  234,
      463,  462,  290,  232,  407,  407,  407,  233,  291,  227,

      291,  461,  460,  408,  227,  224,  224,  224,  224,  224,
      224,   69,  459,   62,   61,  458,  457,   69,  226,  226,
      226,  226,  226,  226,  456,  455,  454,  284,  284,  284,
      284,  284,  284,  293,  293,  293,  293,  293,  293,  284,
      284,  284,  284,  284,  284,  292,  453,  292,  452,  468,
      293,  293,  293,  293,  293,  293,  469,  451,  450,   62,
      449,  448,  447,  284,  284,  284,  284,  284,  284,  148,
      338,  338,  338,  338,  338,  338,  446,  445,  287,  287,
      287,  287,  287,  287,  224,  224,  224,  224,  224,  224,
      287,  287,  287,  287,  287,  287,  472,  407,  407,  407,

      472,  153,  444,  473,  443,  153,  408,  473,  442,  441,
       69,  440,  439,  438,  287,  287,  287,  287,  287,  287,
      437,  436,  435,  434,  433,  153,  432,  431,  430,  429,
      153,  226,  226,  226,  226,  226,  226,  337,  428,  337,
      427,  426,  338,  338,  338,  338,  338,  338,  156,  339,
      425,  339,  156,  424,  340,  340,  340,  340,  340,  340,
      423,  293,  293,  293,  293,  293,  293,  422,  421,  420,
      419,  418,  156,  417,  416,  415,  414,  156,  341,  413,
      412,  411,  341,  338,  338,  338,  338,  338,  338,  340,
      340,  340,  340,  340,  340,  410,  409,  406,  405,  403,

      377,  402,  341,  401,  377,  400,  399,  341,  398,  340,
      340,  340,  340,  340,  340,  397,  396,  395,  394,  393,
      392,  391,  390,  389,  377,  388,  378,  387,  386,  377,
      378,  385,  384,  383,  382,  381,  376,  375,  374,  373,
      372,  371,  370,  369,  368,  367,  366,  365,  364,  363,
      378,  362,  361,  360,  359,  378,   56,   56,   56,   56,
       56,   56,   56,   56,   56,   60,  358,   60,   60,   60,
       60,   60,   60,   60,   68,  357,   68,  356,   68,   68,
       68,   68,   68,  101,  101,  101,  101,   60,   60,  355,
       60,  354,  353,   60,   68,   68,  352,   68,  351,  350,

       68,  154,  349,  154,  154,  154,  154,  154,  154,  154,
      164,  164,  164,  219,  219,  222,  222,  229,  229,  404,
      348,  404,  404,  404,  404,  404,  404,  404,  347,  346,
      345,  344,  343,  342,  342,  336,  335,  334,  333,  332,
      331,  330,  329,  328,  327,  326,  325,  324,  323,  322,
      321,  320,  319,  318,  317,  316,  315,  314,  313,  310,
      309,  308,  307,  306,  305,  304,  303,  302,  301,  300,
      299,  298,  297,  296,  285,  282,  281,  280,  279,  278,
      277,  276,  275,  274,  273,  272,  271,  270,  269,  268,
      267,  266,  265,  264,  263,  262,  261,  260,  259,  256,

      255,  254,  253,  252,  251,  248,  247,  246,  245,  244,
      243,  242,  241,  240,  239,  238,  237,  236,  235,  235,
      228,  228,  220,  102,  217,  102,  212,  211,  206,  202,
      199,  198,  197,  196,  195,  194,  193,  192,  191,  190,
      189,  188,  187,  179,  178,  177,  176,  175,  174,  173,
       69,  170,  169,  163,  151,  147,  139,  138,  135,  130,
      129,  126,  115,  114,  104,   98,   93,   70,   69,   63,
       59,  481,   57,   57,    5,  481,  481,  481,  481,  481,
      481,  481,  481,  481,  481,  481,  481,  481,  481,  481,
      481,  481,  481,  481,  481,  481,  481,  481,  481,  481,

      481,  481,  481,  481,  481,  481,  481,  481,  481,  481,
      481,  481,  481,  481,  481,  481,  481,  481,  481,  481,
      481,  481,  481,  481,  481,  481,  481,  481,  481,  481,
      481,  481,  481,  481,  481,  481,  481,  481,  481,  481,
      481,  481,  481,  481,  481,  481,  481,  481,  481,  481,
      481,  481,  481,  481,  481,  481,  481
    } ;

static const flex_int16_t yy_chk[958] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    7,    7,    7,    8,    8,    8,   10,   12,
       12,   13,   18,   40,   21,   20,   21,   21,   21,   21,

       21,   21,   40,   27,   22,  479,   18,   20,   20,   22,
       13,   29,   29,   32,   39,   42,   82,   32,   42,   22,
       27,   39,   27,   27,   41,   44,   41,   39,   53,   58,
       58,   58,   44,   10,   23,   41,   23,   23,   23,   23,
       23,   23,   60,   68,   82,   36,   36,   36,   47,   47,
       49,   36,   23,   36,   49,   36,   85,   23,   47,   36,
       36,   47,  159,   85,   23,   23,   86,   49,   36,   61,
       61,   61,  105,   61,  128,  132,   23,  102,  137,  105,
       53,  128,   23,  165,   68,   91,  137,   60,  159,   85,
       23,   86,  132,   23,   24,  477,   24,   24,   24,   24,

       24,   24,   62,   62,   62,   62,   90,   61,   88,  165,
       91,   49,   24,   90,   61,   92,  476,   24,   69,   69,
       69,   69,  102,  133,   24,  229,   88,   77,   77,   77,
       77,   77,   77,   92,   88,  130,   24,  475,  133,   90,
       61,   92,   24,   77,   77,  130,  130,  138,   77,  138,
       24,  229,  184,   81,   81,   81,   81,   81,   81,   62,
      184,  144,  142,  142,  142,  474,  142,   77,   77,   81,
       81,  191,  191,   77,   81,   69,  145,   83,  144,   83,
       83,   83,   83,   83,   83,  230,  471,  233,  470,  145,
      145,  145,  145,   81,   81,   83,   84,  113,   84,   81,

      142,   84,   84,   84,   84,   84,   84,  142,  251,  113,
      113,  230,  233,  113,  113,  251,  149,  113,  290,   83,
      467,  145,  464,  462,  113,  149,  149,  149,  149,  152,
      343,  152,  283,  142,  152,  152,  152,  152,  152,  152,
      155,  164,  155,  343,  290,  155,  155,  155,  155,  155,
      155,  157,  157,  157,  157,  157,  157,  149,  158,  158,
      158,  158,  158,  158,  164,  231,  463,  164,  218,  460,
      286,  164,  231,  463,  234,  158,  221,  283,  459,  158,
      458,  218,  218,  218,  218,  221,  221,  221,  221,  164,
      457,  456,  234,  164,  381,  381,  381,  164,  231,  158,

      234,  455,  454,  381,  158,  223,  223,  223,  223,  223,
      223,  286,  453,  218,  219,  452,  451,  221,  225,  225,
      225,  225,  225,  225,  450,  449,  448,  219,  219,  219,
      219,  219,  219,  292,  292,  292,  292,  292,  292,  219,
      219,  219,  219,  219,  219,  232,  445,  232,  444,  468,
      232,  232,  232,  232,  232,  232,  468,  443,  442,  219,
      441,  440,  438,  219,  219,  219,  219,  219,  219,  222,
      337,  337,  337,  337,  337,  337,  437,  436,  222,  222,
      222,  222,  222,  222,  224,  224,  224,  224,  224,  224,
      222,  222,  222,  222,  222,  222,  469,  407,  407,  407,

      472,  224,  435,  469,  434,  224,  407,  472,  433,  432,
      222,  431,  429,  423,  222,  222,  222,  222,  222,  222,
      419,  418,  417,  416,  415,  224,  414,  413,  412,  411,
      224,  226,  226,  226,  226,  226,  226,  288,  403,  288,
      402,  400,  288,  288,  288,  288,  288,  288,  226,  289,
      399,  289,  226,  397,  289,  289,  289,  289,  289,  289,
      396,  293,  293,  293,  293,  293,  293,  395,  394,  393,
      392,  391,  226,  390,  389,  388,  387,  226,  293,  386,
      385,  384,  293,  338,  338,  338,  338,  338,  338,  339,
      339,  339,  339,  339,  339,  383,  382,  380,  379,  375,

      338,  374,  293,  373,  338,  366,  365,  293,  361,  340,
      340,  340,  340,  340,  340,  360,  359,  358,  357,  356,
      355,  354,  353,  352,  338,  351,  340,  350,  349,  338,
      340,  348,  347,  346,  345,  344,  336,  334,  333,  331,
      330,  329,  328,  327,  326,  324,  323,  322,  321,  319,
      340,  318,  317,  316,  313,  340,  482,  482,  482,  482,
      482,  482,  482,  482,  482,  483,  312,  483,  483,  483,
      483,  483,  483,  483,  484,  311,  484,  310,  484,  484,
      484,  484,  484,  485,  485,  485,  485,  486,  486,  309,
      486,  308,  307,  486,  487,  487,  306,  487,  305,  304,

      487,  488,  303,  488,  488,  488,  488,  488,  488,  488,
      489,  489,  489,  490,  490,  491,  491,  492,  492,  493,
      302,  493,  493,  493,  493,  493,  493,  493,  301,  300,
      299,  297,  296,  295,  294,  285,  282,  281,  279,  278,
      277,  276,  275,  274,  273,  272,  271,  270,  269,  268,
      266,  264,  263,  260,  259,  258,  257,  254,  252,  250,
      249,  248,  247,  246,  245,  244,  243,  242,  241,  240,
      239,  238,  237,  236,  220,  217,  216,  215,  214,  213,
      212,  211,  210,  209,  208,  207,  206,  205,  204,  203,
      202,  200,  199,  197,  196,  195,  194,  193,  192,  190,

      189,  188,  187,  186,  185,  183,  182,  181,  180,  179,
      178,  177,  176,  175,  174,  173,  172,  171,  168,  167,
      162,  161,  147,  143,  139,  136,  135,  134,  131,  129,
      126,  125,  124,  123,  122,  121,  120,  119,  118,  117,
      116,  115,  114,  112,  111,  110,  109,  108,  107,  106,
      103,  100,   96,   87,   76,   63,   51,   50,   48,   46,
       45,   43,   38,   37,   35,   28,   25,   17,   14,   11,
        9,    5,    4,    3,  481,  481,  481,  481,  481,  481,
      481,  481,  481,  481,  481,  481,  481,  481,  481,  481,
      481,  481,  481,  481,  481,  481,  481,  481,  481,  481,

      481,  481,  481,  481,  481,  481,  481,  481,  481,  481,
      481,  481,  481,  481,  481,  481,  481,  481,  481,  481,
      481,  481,  481,  481,  481,  481,  481,  481,  481,  481,
      481,  481,  481,  481,  481,  481,  481,  481,  481,  481,
      481,  481,  481,  481,  481,  481,  481,  481,  481,  481,
      481,  481,  481,  481,  481,  481,  481
    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[120] =
    {   0,
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 
        };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "C_grammar.l"
/****************************************************************************************************/
/* C11 lexer file from https://www.quut.com/c/ANSI-C-grammar-l-2011.html                            */
/* Flex documentation: https://westes.github.io/flex/manual/index.html                        */
/****************************************************************************************************/
/* definition section */
#line 16 "C_grammar.l"
#ifdef _MSC_VER
    #define strdup_safe(char_ptr) _strdup(char_ptr)
#else
    #define strdup_safe(char_ptr) strdup(char_ptr)
#endif

#include <stdio.h>
#include <limits.h>

#include "C_grammar.tab.h"

extern int in_tag_namespace;
extern int is_typedef_name(char*);
extern long int TARGET_LONG_MAX;

void read_comment();
int differentiate_identifiers(char *);
void wrap_integer_constants(char *, char *, char **);
void wrap_floating_point_constants(char *, char *, char **);
void add_missing_zero(char *, char **);

int open_parens = 0; /* Declaration in the definitions section */

#line 876 "lex.yy.c"

#line 878 "lex.yy.c"

#define INITIAL 0
#define ATTRIBUTE 1

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 59 "C_grammar.l"

#line 61 "C_grammar.l"
        /* rules section */
#line 1100 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 482 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 875 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 62 "C_grammar.l"
{ read_comment(); }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 63 "C_grammar.l"
{ /* consume //-comment */ }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 64 "C_grammar.l"
{ /* Ignore the entire line after `#pragma` */ }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 65 "C_grammar.l"
{ /* Ignoring GCC keyword __extension__ that disables compiler warnings about non-compliant features */ }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 66 "C_grammar.l"
{ /* Ignoring all GCC __attribute__ at our peril obviously */ 
                                             open_parens = 2; /* Start with the initial two opening parentheses */
                                             BEGIN(ATTRIBUTE); /* Enter the ATTRIBUTE start condition */
                                            }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 70 "C_grammar.l"
{ 
    if (yytext[0] == '(') { /* Increment for each additional opening parenthesis */
        open_parens++;
    } 
    else if (yytext[0] == ')') { /* Decrement for each closing parenthesis */
        open_parens--;
        if (open_parens == 0) {
            BEGIN(INITIAL); /* Exit ATTRIBUTE mode after the matched parentheses are balanced */
        }
    }
    /* Otherwise, continue reading characters in ATTRIBUTE mode */
}
	YY_BREAK
case YY_STATE_EOF(ATTRIBUTE):
#line 82 "C_grammar.l"
{ /* Handle unexpected EOF */
    fprintf(stderr, "Error: Unclosed __attribute__(( found.\n");
    exit(1);
}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 86 "C_grammar.l"
{ return(AUTO); }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 87 "C_grammar.l"
{ return(BREAK); }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 88 "C_grammar.l"
{ return(CASE); }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 89 "C_grammar.l"
{ return(CHAR); }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 90 "C_grammar.l"
{ return(CONST); }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 91 "C_grammar.l"
{ return(CONTINUE); }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 92 "C_grammar.l"
{ return(DEFAULT); }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 93 "C_grammar.l"
{ return(DO); }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 94 "C_grammar.l"
{ return(DOUBLE); }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 95 "C_grammar.l"
{ return(ELSE); }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 96 "C_grammar.l"
{ return(ENUM); }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 97 "C_grammar.l"
{ return(EXTERN); }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 98 "C_grammar.l"
{ return(FLOAT); }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 99 "C_grammar.l"
{ return(FOR); }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 100 "C_grammar.l"
{ return(GOTO); }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 101 "C_grammar.l"
{ return(IF); }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 102 "C_grammar.l"
{ return(INLINE); }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 103 "C_grammar.l"
{ return(INLINE); }     //GCC version of INLINE
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 104 "C_grammar.l"
{ return(INT); }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 105 "C_grammar.l"
{ return(LONG); }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 106 "C_grammar.l"
{ return(REGISTER); }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 107 "C_grammar.l"
{ return(RESTRICT); }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 108 "C_grammar.l"
{ return(RESTRICT); }   //GCC version of RESTRICT
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 109 "C_grammar.l"
{ return(RETURN); }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 110 "C_grammar.l"
{ return(SHORT); }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 111 "C_grammar.l"
{ return(SIGNED); }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 112 "C_grammar.l"
{ return(SIZEOF); }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 113 "C_grammar.l"
{ return(STATIC); }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 114 "C_grammar.l"
{ return(STRUCT); }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 115 "C_grammar.l"
{ return(SWITCH); }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 116 "C_grammar.l"
{ return(TYPEDEF); }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 117 "C_grammar.l"
{ return(UNION); }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 118 "C_grammar.l"
{ return(UNSIGNED); }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 119 "C_grammar.l"
{ return(VOID); }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 120 "C_grammar.l"
{ return(VOLATILE); }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 121 "C_grammar.l"
{ return(WHILE); }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 122 "C_grammar.l"
{ return(INT128); }     //GCC builtin 128-bit integer type
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 123 "C_grammar.l"
{ return(FLOAT128); }   //GCC builtin 128-bit floating-point type
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 124 "C_grammar.l"
{ return(VA_LIST); }    //GCC builtin variable argument list type
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 125 "C_grammar.l"
{ return ALIGNAS; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 126 "C_grammar.l"
{ return ALIGNOF; }
	YY_BREAK
case 48:
/* rule 48 can match eol */
YY_RULE_SETUP
#line 127 "C_grammar.l"
{ return ATOMIC_SPECIFIER; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 128 "C_grammar.l"
{ return ATOMIC; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 129 "C_grammar.l"
{ return BOOL; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 130 "C_grammar.l"
{ return COMPLEX; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 131 "C_grammar.l"
{ return GENERIC; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 132 "C_grammar.l"
{ return IMAGINARY; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 133 "C_grammar.l"
{ return NORETURN; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 134 "C_grammar.l"
{ return STATIC_ASSERT; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 135 "C_grammar.l"
{ return THREAD_LOCAL; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 136 "C_grammar.l"
{ return FUNC_NAME; }   //__PRETTY_FUNCTION__ is a GCC extension: an enhanced version of __func__; which we ignore 
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 137 "C_grammar.l"
{ return FUNC_NAME; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 139 "C_grammar.l"
{yylval.id = strdup_safe(yytext);
                             if (!in_tag_namespace && is_typedef_name(yylval.id)) {
                                //if (debugMode) printf("Debug: returning the typedef %s from lexer\n", yytext);
                                return TYPEDEF_NAME;
                             }
                             return IDENTIFIER;
                            }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 147 "C_grammar.l"
{wrap_integer_constants("16'", &yytext[2], &yylval.id);     //hexadecimal integer
                             return I_CONSTANT;
                            }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 150 "C_grammar.l"
{wrap_integer_constants("", yytext, &yylval.id);            //decimal integer
                             return I_CONSTANT;
                            }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 154 "C_grammar.l"
{if (isdigit(yytext[1])) wrap_integer_constants("8'", &yytext[1], &yylval.id);  //octal integer 
                             else { //the second char after 0 is not a digit (it's /0, ofr an IS (u|U)(l|L|ll|LL) char), so it's just the constant 0, rather than a true octal 
                                yylval.id = (char*)malloc(7);
                                strcpy(yylval.id, "int(0)");    
                             }
                             return I_CONSTANT;
                            }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 161 "C_grammar.l"
{yylval.id = strdup_safe(yytext); return I_CONSTANT;}   //single characters
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 163 "C_grammar.l"
{wrap_floating_point_constants("", yytext, &yylval.id);     //Decimal floating-point constants with an exponent.
                             return F_CONSTANT;
                            }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 166 "C_grammar.l"
{wrap_floating_point_constants("", yytext, &yylval.id);     //Decimal floating-point constants with a fractional part.
                             return F_CONSTANT;
                            }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 169 "C_grammar.l"
{char* added_0;
                             add_missing_zero(yytext, &added_0);
                             wrap_floating_point_constants("", added_0, &yylval.id);         //Decimal floating-point constants with a fractional part.
                             return F_CONSTANT;
                            }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 174 "C_grammar.l"
{wrap_floating_point_constants("hexadecimal", yytext, &yylval.id);  //Hexadecimal floating-point constants: will fail parser in ECLiPSe
                             return F_CONSTANT;
                            }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 177 "C_grammar.l"
{wrap_floating_point_constants("hexadecimal", yytext, &yylval.id);    //Hexadecimal floating-point constants with a fractional part.: will fail parser in ECLiPSe
                             return F_CONSTANT;
                            }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 180 "C_grammar.l"
{char* added_0;
                             add_missing_zero(yytext, &added_0);
                             wrap_floating_point_constants("hexadecimal", added_0, &yylval.id);   //Hexadecimal floating-point constants with digits before the decimal point, but none after. : will fail parser in ECLiPSe
                             return F_CONSTANT;
                            }
	YY_BREAK
case 70:
/* rule 70 can match eol */
YY_RULE_SETUP
#line 186 "C_grammar.l"
{if (yytext[0] == 'L') { //a wide string constant
                                        size_t const size = strlen("wide_string()") + strlen(yytext) - 1 + 1;
                                        yylval.id = (char*)malloc(size);
                                        sprintf_safe(yylval.id, size, "wide_string(%s)", &yytext[1]);      //copy from yytext[1] to remove 'L' prefix 
                                     } else {
                                        yylval.id = strdup_safe(yytext);
                                     }
                                     return STRING_LITERAL;
                                    }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 196 "C_grammar.l"
{ return ELLIPSIS; }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 197 "C_grammar.l"
{ return RIGHT_ASSIGN; }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 198 "C_grammar.l"
{ return LEFT_ASSIGN; }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 199 "C_grammar.l"
{ return ADD_ASSIGN; }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 200 "C_grammar.l"
{ return SUB_ASSIGN; }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 201 "C_grammar.l"
{ return MUL_ASSIGN; }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 202 "C_grammar.l"
{ return DIV_ASSIGN; }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 203 "C_grammar.l"
{ return MOD_ASSIGN; }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 204 "C_grammar.l"
{ return AND_ASSIGN; }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 205 "C_grammar.l"
{ return XOR_ASSIGN; }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 206 "C_grammar.l"
{ return OR_ASSIGN; }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 207 "C_grammar.l"
{ return RIGHT_OP; }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 208 "C_grammar.l"
{ return LEFT_OP; }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 209 "C_grammar.l"
{ return INC_OP; }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 210 "C_grammar.l"
{ return DEC_OP; }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 211 "C_grammar.l"
{ return PTR_OP; }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 212 "C_grammar.l"
{ return AND_OP; }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 213 "C_grammar.l"
{ return OR_OP; }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 214 "C_grammar.l"
{ return LE_OP; }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 215 "C_grammar.l"
{ return GE_OP; }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 216 "C_grammar.l"
{ return EQ_OP; }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 217 "C_grammar.l"
{ return NE_OP; }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 218 "C_grammar.l"
{ return ';'; }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 219 "C_grammar.l"
{ return '{'; }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 220 "C_grammar.l"
{ return '}'; }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 221 "C_grammar.l"
{ return ','; }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 222 "C_grammar.l"
{ return ':'; }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 223 "C_grammar.l"
{ return '='; }
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 224 "C_grammar.l"
{ return '('; }
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 225 "C_grammar.l"
{ return ')'; }
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 226 "C_grammar.l"
{ return '['; }
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 227 "C_grammar.l"
{ return ']'; }
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 228 "C_grammar.l"
{ return '.'; }
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 229 "C_grammar.l"
{ return '&'; }
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 230 "C_grammar.l"
{ return '!'; }
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 231 "C_grammar.l"
{ return '~'; }
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 232 "C_grammar.l"
{ return '-'; }
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 233 "C_grammar.l"
{ return '+'; }
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 234 "C_grammar.l"
{ return '*'; }
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 235 "C_grammar.l"
{ return '/'; }
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 236 "C_grammar.l"
{ return '%'; }
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 237 "C_grammar.l"
{ return '<'; }
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 238 "C_grammar.l"
{ return '>'; }
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 239 "C_grammar.l"
{ return '^'; }
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 240 "C_grammar.l"
{ return '|'; }
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 241 "C_grammar.l"
{ return '?'; }
	YY_BREAK
case 117:
/* rule 117 can match eol */
YY_RULE_SETUP
#line 243 "C_grammar.l"
{ /* whitespaces (including new lines) separate tokens */ }
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 244 "C_grammar.l"
{ /* discard bad characters */ }
	YY_BREAK
case 119:
YY_RULE_SETUP
#line 246 "C_grammar.l"
ECHO;
	YY_BREAK
#line 1826 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 482 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 482 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 481);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 246 "C_grammar.l"

/* user code section */
int yywrap(void)        /* called at end of input */
{
    return 1;           /* terminate now */
}

void read_comment() {
    int c;

    while ((c = input()) != 0)
        if (c == '*')
        {
            while ((c = input()) == '*')
                ;

            if (c == '/')
                return;

            if (c == 0)
                break;
        }
}

//add hexademical or octal wrapper and handle u|l|ll variations
void wrap_integer_constants(char *wrapper, char *input, char **output) {
    int current = strlen(input)-1;
    int has_u = 0, has_l = 0, has_ll = 0;
    int has_suffix = 1;

    while (has_suffix && current >= 0) {    //start from the end and move back until non u|U|l|L character is met
        switch (input[current]) {
            case 'u':
            case 'U':
                has_u = 1;
                break;
            case 'l':
            case 'L':
                if (current >0 && (input[current-1] == 'l' || input[current-1] == 'L')) {
                    has_ll = 1;
                    current--;  //skip the other 'l' or 'LL'
                }
                else has_l = 1;
                break;
            default:
                has_suffix = 0;  
        }
        if (has_suffix) current--;
    }
    int has_wrapper = strcmp(wrapper, "");
    //calculating the length of the result: length of the wrapper + length of the prefix, the suffix, the underscore, the parenthesis
    int size = strlen(wrapper) + current+1 + 1 + has_u*strlen("unsigned") + has_l*strlen("long") + has_ll*strlen("long_long") + has_u*has_l + has_u*has_ll + (has_u || has_l || has_ll ? 2 : 0);

    char format_string[100];
    strcpy(format_string, "");

    if (!has_u && !has_l && !has_ll) {              //has no suffix, type depends on value
        unsigned long constant = strtoul(input, NULL, 0);         //the 0 enables automatic detection of base: decimal, octal or hexadecimal
        if (constant <= INT_MAX) {
            strcat(format_string, "int(");
            size += strlen("int()");
        } else if (has_wrapper && constant <= UINT_MAX) {   //different rule for octals and hexademcimals
            strcat(format_string, "unsigned(");
            size += strlen("unsigned()");
        }
         else if (constant <= TARGET_LONG_MAX) {          //don't use LONG_MAX, values dependents on the target memory model size (32 vs 64 bits) of the program under test, not of the compiler used to generate the parser
            strcat(format_string, "long(");
            size += strlen("long()");
        } else {
            strcat(format_string, "unsigned_long(");   //todo check how long long constants without suffix are handled in gcc/ansi C currently set as unsigned long which is big enough
            size += strlen("unsigned_long()");
        }   
    }
    else if (has_u && !has_l && !has_ll) 
        strcat(format_string, "unsigned(");
    else if (has_u && has_l && !has_ll) 
        strcat(format_string, "unsigned_long(");
    else if (has_u && !has_l && has_ll) 
        strcat(format_string, "unsigned_long_long(");
    else if (!has_u && has_l && !has_ll) 
        strcat(format_string, "long(");
    else if (!has_u && !has_l && has_ll) 
        strcat(format_string, "long_long(");

    if (has_wrapper) strcat(format_string, "%s");
    
    strcat(format_string, "%.*s)");

    *output = (char *)malloc(size);
    if (has_wrapper) {
        snprintf(*output, size, format_string, wrapper, current + 1, input);
    } else {
        snprintf(*output, size, format_string, current + 1, input);
    }
}

//add hexademical wrapper if present and handle f|F|l|L variations
void wrap_floating_point_constants(char * wrapper, char * input, char ** output) {
    int current = strlen(input)-1;
    int has_f = 0, has_l = 0, is_d = 0;
    int has_suffix = 1;
    switch (input[current]) {
        case 'f':
        case 'F':
            has_f = 1;
            break;
        case 'l':
        case 'L':
            has_l = 1;
            break;
        default:
            is_d = 1;
            has_suffix = 0;
    }
    if (has_suffix) current--;
    int has_wrapper = strcmp(wrapper, "");
    //calculating the length of the result: length of the wrapper + 2 parentheses + length of the prefix, the suffix, the parenthesis
    int size = (has_wrapper ? strlen(wrapper) + 2 : 0) + current+1 + 1 + is_d*strlen("double") + has_f*strlen("float") + has_l*strlen("long_double") + (has_f || has_l || is_d ? 2 : 0);
    *output = (char *)malloc(size);
    char format_string[100];
    if (has_wrapper) strcpy(format_string, "%s("); //starts with the floating point kind wrapper
    else strcpy(format_string, "");
    if (is_d)
        strcat(format_string, "double(%.*s)");      //double is the default type for floating points literals
    else if (has_f) 
        strcat(format_string, "float(%.*s)");
    else if (has_l) 
        strcat(format_string, "long_double(%.*s)");
    if (has_wrapper) {
        strcat(format_string, ")"); //adds the wrapper end parenthesis
        snprintf(*output, size, format_string, wrapper, current + 1, input);
    } else {
        snprintf(*output, size, format_string, current + 1, input);
    }
}

//float has no digit after decimal point: need to add 0
void add_missing_zero(char * input, char ** output) {
    size_t len = strlen(input);
    *output = (char*)malloc(len + 1 + 1); // +1 for extra '0'
    strcpy(*output, input);
    char* decimal_point = strchr(*output, '.');
    char* suffix = strpbrk(decimal_point, "eElL"); //returns pointer to first occurrence of character
    if (suffix == NULL) {// No suffix, so it's the end of the string
        suffix = *output + strlen(*output);
    }
    size_t decimal_pos = decimal_point - *output;
    memmove(decimal_point + 2, decimal_point + 1, len - decimal_pos); //copy everything after the decimal point to +1 location
    (*output)[decimal_pos + 1] = '0';    //add the 'missing' 0
}
