prolog_c([function([int], function(Main, []), [], 
cmp_stmts([
declaration([double], [initialised(D_testcomp, hexadecimal(hex_float(double,1.FFFFFE,+127)))]), 
declaration([double], [initialised(D_more, hexadecimal(hex_float(double,1.19999a,0)))]), 
declaration([float], [initialised(F1, float(123.0))]), 
declaration([float], [initialised(F2, float(123.0))]), 
declaration([double], [initialised(D1, double(123.0))]), 
declaration([double], [initialised(D2, double(123.0))]), 
declaration([double], [initialised(D3, double(123.0E10))]), 
declaration([long, double], [initialised(Ld1, long_double(123.0E10))]), 
declaration([long, double], [initialised(Ld2, long_double(123.0))]), 
declaration([long, double], [initialised(Ld3, long_double(123.0))]), 
declaration([float], [initialised(F3, float(1e2))]), 
declaration([float], [initialised(F4, float(1E2))]), 
declaration([double], [initialised(D4, double(1e2))]), 
declaration([double], [initialised(D5, double(1E2))]), 
declaration([long, double], [initialised(Ld4, long_double(1e2))]), 
declaration([long, double], [initialised(Ld5, long_double(1E2))]), 
declaration([float], [initialised(F5, hexadecimal(hex_float(float,1,2)))]), 
declaration([double], [initialised(D6, hexadecimal(hex_float(double,1,2)))]), 
declaration([long, double], [initialised(Ld6, hexadecimal(hex_float(long double,1,2)))]), 
declaration([float], [initialised(F6, float(1.0E1))]), 
declaration([double], [initialised(D7, double(1.0E1))]), 
declaration([long, double], [initialised(Ld7, long_double(1.0E1))]), 
declaration([float], [initialised(F7, hexadecimal(hex_float(float,1.0,0)))]), 
declaration([float], [initialised(F8, hexadecimal(hex_float(float,1.0,1)))]), 
declaration([float], [initialised(F9, hexadecimal(hex_float(float,1.0,2)))]), 
declaration([float], [initialised(F10, hexadecimal(hex_float(float,1.0,3)))]), 
declaration([float], [initialised(F11, hexadecimal(hex_float(float,1.0,3)))]), 
declaration([float], [initialised(F12, hexadecimal(hex_float(float,1.4,1)))]), 
declaration([float], [initialised(F13, hexadecimal(hex_float(float,1.8,1)))]), 
declaration([float], [initialised(F14, hexadecimal(hex_float(float,1.C,2)))]), 
declaration([float], [initialised(F15, hexadecimal(hex_float(float,1.f,2)))]), 
declaration([double], [initialised(D8, hexadecimal(hex_float(double,1.0,0)))]), 
declaration([double], [initialised(D9, hexadecimal(hex_float(double,1.0,1)))]), 
declaration([double], [initialised(D10, hexadecimal(hex_float(double,1.0,2)))]), 
declaration([double], [initialised(D11, hexadecimal(hex_float(double,1.0,3)))]), 
declaration([double], [initialised(D12, hexadecimal(hex_float(double,1.4,1)))]), 
declaration([double], [initialised(D13, hexadecimal(hex_float(double,1.8,1)))]), 
declaration([double], [initialised(D14, hexadecimal(hex_float(double,1.C,2)))]), 
declaration([double], [initialised(D15, hexadecimal(hex_float(double,1.f,2)))]), 
declaration([long, double], [initialised(Ld8, hexadecimal(hex_float(long double,1.0,0)))]), 
declaration([long, double], [initialised(Ld9, hexadecimal(hex_float(long double,1.0,1)))]), 
declaration([long, double], [initialised(Ld10, hexadecimal(hex_float(long double,1.0,2)))]), 
declaration([long, double], [initialised(Ld11, hexadecimal(hex_float(long double,1.0,3)))]), 
declaration([long, double], [initialised(Ld12, hexadecimal(hex_float(long double,1.4,1)))]), 
declaration([long, double], [initialised(Ld13, hexadecimal(hex_float(long double,1.8,1)))]), 
declaration([long, double], [initialised(Ld14, hexadecimal(hex_float(long double,1.C,2)))]), 
declaration([long, double], [initialised(Ld15, hexadecimal(hex_float(long double,1.f,2)))])
]))
]).